# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: Swift Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6"      

      - name: Verify Swift version
        run: swift --version

      - name: Run Tests
        run: swift test

